; https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/cfg/Custom_Clash.ini
; https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash
[custom]

; 規則集定義
ruleset=🎯 全球直連,[]GEOSITE,private
ruleset=🎯 全球直連,[]GEOIP,private,no-resolve
;直連
ruleset=🎯 全球直連,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800
ruleset=🎯 全球直連,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
ruleset=🎯 全球直連,https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Direct.list,28800
;代理
ruleset=🚀 節點選擇,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.yaml,28800
ruleset=🚀 節點選擇,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical_IP.yaml,28800
;直連
ruleset=🎯 全球直連,[]GEOSITE,apple-cn
ruleset=🎯 全球直連,[]GEOSITE,google-cn
ruleset=🎯 全球直連,[]GEOSITE,category-games@cn
ruleset=🎯 全球直連,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml,28800
ruleset=🎯 全球直連,[]GEOSITE,category-game-platforms-download
ruleset=🎯 全球直連,[]GEOSITE,category-public-tracker
;Block
ruleset=🚀 節點選擇,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/preBlock.yaml,28800
ruleset=🛑 Block,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Block.yaml,28800
;VPN
ruleset=🛜 VPN,clash-classic:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/VPN/ExpressVPN.yaml,28800
;Secure
ruleset=🔨 Secure,clash-classic:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Secure/IBKR.yaml,28800
ruleset=🔨 Secure,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Secure/PasswordManager.yaml,28800
ruleset=🔨 Secure,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Secure/Payment.yaml,28800
ruleset=🔨 Secure,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Secure/Mail.yaml,28800
ruleset=🔨 Secure,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Secure/Others.yaml,28800
;Crypto
ruleset=🔨 Crypto,[]GEOSITE,category-cryptocurrency
ruleset=🔨 Crypto,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Crypto/Crypto.list,28800
ruleset=🔨 Crypto,clash-classic:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Crypto/Others.yaml,28800
ruleset=🔨 Crypto,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Crypto/Exchange.yaml,28800
ruleset=🔨 Crypto,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Crypto/Blockchain.yaml,28800
ruleset=🔨 Crypto,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Crypto/Wallet.yaml,28800
;Others
ruleset=🚀 節點選擇,https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/SelfProxy.list,28800
ruleset=☁️ CloudStorage,clash-domain:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/CloudStorage.yaml,28800
ruleset=🔨 Entertainment,https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Entertainment.list,28800
ruleset=💬 Telegram,[]GEOSITE,telegram
ruleset=💬 其他即時通訊,[]GEOSITE,category-communication
ruleset=🔨 Low-Latency,clash-classic:https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/Low-Latency.yaml,2880
ruleset=🌐 社群媒體,[]GEOSITE,category-social-media-!cn
ruleset=🤖 AI,[]GEOSITE,category-ai-!cn
ruleset=👨🏿‍💻 GitHub,[]GEOSITE,github
ruleset=▶️ YouTube,[]GEOSITE,youtube
ruleset=🎻 Spotify,[]GEOSITE,spotify
ruleset=🍎 Apple,[]GEOSITE,apple
ruleset=Ⓜ️ Microsoft,[]GEOSITE,microsoft
ruleset=🇬 Google,[]GEOSITE,google
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=🎮 PlayStation,[]GEOSITE,playstation
ruleset=🎮 其他遊戲平台,[]GEOSITE,category-games
ruleset=🔨 Entertainment,[]GEOSITE,category-entertainment
ruleset=🛒 E-commerce,[]GEOSITE,category-ecommerce
ruleset=🛒 E-commerce,https://raw.githubusercontent.com/abcat230/rule/refs/heads/main/rules/Custom/E-Commerce.list,28800
ruleset=🚀 節點選擇,[]GEOSITE,gfw
ruleset=🇬 Google,[]GEOIP,google,no-resolve
ruleset=💬 Telegram,[]GEOIP,telegram,no-resolve
ruleset=🌐 社群媒體,[]GEOIP,twitter,no-resolve
ruleset=🌐 社群媒體,[]GEOIP,facebook,no-resolve
ruleset=🇬 Google,[]GEOIP,google,no-resolve
ruleset=🎯 全球直連,[]GEOSITE,cn
ruleset=🎯 全球直連,[]GEOIP,cn,no-resolve
ruleset=🐟 漏網之魚,[]FINAL


; Flow
custom_proxy_group=🚀 節點選擇`select`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🛜 VPN`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=▶️ YouTube`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🤖 AI`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=💬 Telegram`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=💬 其他即時通訊`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🌐 社群媒體`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=☁️ CloudStorage`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🔨 Low-Latency`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=Ⓜ️ Microsoft`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🇬 Google`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🎮 PlayStation`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🎮 其他遊戲平台`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🎻 Spotify`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🔨 Entertainment`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🛒 E-commerce`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🔨 Secure`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🔨 Crypto`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
custom_proxy_group=🐟 漏網之魚`select`[]🚀 節點選擇`[]🔨 自建01`[]🔨 EdgeTunnel`[]🇭🇰 香港`[]🇺🇸 美國`[]🇯🇵 日本`[]🌐 其他`[]♻️ 自動選擇`[]🐸 手動切換`[]DIRECT
; Node
custom_proxy_group=🔨 EdgeTunnel`url-test`(EdgeTunnel)`https://cp.cloudflare.com/generate_204`300,50
custom_proxy_group=🔨 自建01`url-test`(自建01)`https://cp.cloudflare.com/generate_204`300,50
custom_proxy_group=🇭🇰 香港`url-test`(🇭🇰|港|\bHK\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美國`url-test`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🌐 其他`url-test`(^(?!.*(🇭🇰|港|\bHK\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌|🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC|🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)).*)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🐸 手動切換`select`^(?!.*(佔位)).*$
custom_proxy_group=♻️ 自動選擇`url-test`^(?!.*(佔位)).*$`https://cp.cloudflare.com/generate_204`300,50
custom_proxy_group=🎯 全球直連`select`[]DIRECT
custom_proxy_group=🛑 Block`select`[]REJECT
; 启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
