name: Validate rules

on:
  push:
    paths:
      - '**/*.list'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/*.list'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run validator
        run: |
          chmod +x ./scripts/validate_rules.sh
          ./scripts/validate_rules.sh