name: Validate rules

on:
  push:
    paths:
      - '**/*.list'
      - 'scripts/**'
      - 'config/Clash/Custom_Clash.ini'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/*.list'
      - 'scripts/**'
      - 'config/Clash/Custom_Clash.ini'
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up shell
        run: |
          # ensure bash is available
          bash --version

      - name: Make validator executable
        run: chmod +x ./scripts/validate_rules.sh

      - name: Run validator
        run: ./scripts/validate_rules.sh
